import style from './layout.module.css'

import BottomSection from "@/components/LayoutComponents/BottomSection"
import Navbar from "@/components/LayoutComponents/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en" className={style.main}>
      <Navbar />
      <body>{children}</body>
      <BottomSection />
    </html>
  )
}
